---
- name: Install PostGIS packages
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql-9.3-postgis-2.1
    - libxml2-dev
    - libxslt1-dev
    - libgeos-c1

- name: Install CKAN spatial extension to virtualenv
  pip: name='git+https://github.com/okfn/ckanext-spatial.git@stable#egg=ckanext-spatial' virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

- name: Install Python Requirements
  pip: requirements=/usr/lib/ckan/default/src/ckanext-spatial/pip-requirements.txt virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

- name: Create spatial db
  command: /usr/lib/ckan/default/bin/paster --plugin=ckanext-spatial spatial initdb 4326 --config=/etc/ckan/default/development.ini
- name: Reload Apache
  service: name=apache2 state=reloaded