---
- name: Install Requiered packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - rabbitmq-server
    - redis-server
    - supervisor

- name: Install CKAN remote harvest extension
  pip: name='git+https://github.com/okfn/ckanext-harvest.git@stable#egg=ckanext-harvest' virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

- name: Install CKAN remote harvest Python dependencies
  pip: requirements=/usr/lib/ckan/default/src/ckanext-harvest/pip-requirements.txt virtualenv=/usr/lib/ckan/default virtualenv_site_packages=no

- name: Creating necessary tables in the database
  command: chdir=/etc/ckan/default /usr/lib/ckan/default/bin/paster --plugin=ckanext-harvest harvester initdb --config=production.ini
  
- name: Create harvester log directory
  file: path=/var/log/ckan/harvester/ state=directory
  
- name: Create supervisor conf file
  copy: src=ckan_harvesting.conf dest=/etc/supervisor/conf.d/ force=yes
  
- name: Start supervisor service
  service: name=supervisor state=restarted
  
- name: Create crontab entry
  cron: name="Run harvesters" minute="*/15" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-harvest harvester run --config=/etc/ckan/default/production.ini"